### ISSUE TITLE
zstd.ZstdError: error determining content size from frame header

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [fohristiwhirl/halite3_reload#1]
I downloaded [replay.json.hlt.zip](https://github.com/fohristiwhirl/halite3_reload/files/2507100/replay.json.hlt.zip) (please unzip) from the official web editor:

![image](https://user-images.githubusercontent.com/733573/47377663-34be8480-d6f6-11e8-902e-9f8faca0d8cf.png)

Running `python halite3_reload/reload.py ~/Desktop/replay.json.hlt 0 ./MyBot` gives:

```
$ python halite3_reload/reload.py ~/Desktop/replay.json.hlt 0 ./MyBot
Traceback (most recent call last):
  File "halite3_reload/reload.py", line 305, in <module>
    main()
  File "halite3_reload/reload.py", line 232, in main
    j = dctx.decompress(compressed)
zstd.ZstdError: error determining content size from frame header
```

Ubuntu 16.04, pip freeze:
```
$ pip freeze
agents==1.1.0
asn1crypto==0.22.0
atari-py==0.1.1
attrs==17.3.0
autobahn==17.10.1
Automat==0.6.0
azure==1.0.3
azure-common==1.1.8
azure-mgmt==0.20.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.1
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==2.0.0
azure-mgmt-resource==0.20.1
azure-mgmt-storage==0.20.0
azure-nspkg==2.0.0
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.2
azure-storage==0.20.3
backcall==0.1.0
bleach==1.5.0
cached-property==1.3.1
cairocffi==0.8.0
CairoSVG==2.1.1
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
colorama==0.3.9
conda==4.3.30
constantly==15.1.0
cpp-coveralls==0.4.0
cryptography==1.8.1
cssselect2==0.2.1
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
dill==0.2.7.1
djangoql==0.8.8
docker==3.0.1
docker-py==1.10.3
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
entrypoints==0.2.3
enum34==1.1.6
fastzbarlight==0.0.14
freezegun==0.3.9
future==0.16.0
go-vncdriver==0.4.19
gym==0.9.6
gym-retro==0.5.4
html5lib==0.9999999
hyperlink==17.3.1
idna==2.6
imageio==2.2.0
incremental==17.5.0
ipykernel==4.8.2
ipython==6.3.1
ipython-genutils==0.2.0
ipywidgets==7.2.1
jedi==0.12.0
Jinja2==2.10
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
mpi4py==3.0.0
mujoco-py==0.5.7
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.1
numpy==1.14.1
olefile==0.44
packaging==16.8
pandocfilters==1.4.2
parso==0.2.0
pdfrw==0.4
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.0.0
ply==3.11
ppaquette-gym-super-mario==0.0.5
progressbar2==3.34.3
prompt-toolkit==1.0.15
protobuf==3.5.1
ptyprocess==0.5.2
pycosat==0.6.2
pycparser==2.17
pyglet==1.3.1
Pygments==2.2.0
PyOpenGL==3.1.0
pyOpenSSL==17.0.0
pyparsing==2.1.4
Pyphen==0.9.4
python-dateutil==2.6.1
python-utils==2.2.0
pytz==2018.3
PyYAML==3.12
pyzmq==16.0.3
qtconsole==4.3.1
requests==2.18.4
ruamel.yaml==0.15.34
scipy==1.0.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
tensorflow==1.4.0
tensorflow-tensorboard==0.4.0
terminado==0.8.1
testpath==0.3.1
texttable==0.8.8
tinycss2==0.6.1
tornado==5.0.2
tqdm==4.19.4
traitlets==4.3.2
Twisted==17.9.0
txaio==2.8.2
ujson==1.35
universe==0.21.5
urllib3==1.22
wcwidth==0.1.7
WeasyPrint==0.41
webencodings==0.5.1
websocket-client==0.46.0
Werkzeug==0.14.1
widgetsnbextension==3.2.1
zmq==0.0.0
zope.interface==4.4.3
zstandard==0.10.1

```

**Comment by rooklift** [comment]
This replay is an uncompressed JSON file. Since this script is a quick hack, it just checks file extension to decide what to do. You can load it by renaming it to `replay.json`.

**Comment by AdamStelmaszczyk** [comment]
Thanks, after renaming:

```
$ python halite3_reload/reload.py ~/Desktop/replay.json 0 ./MyBot
Traceback (most recent call last):
  File "halite3_reload/reload.py", line 305, in <module>
    main()
  File "halite3_reload/reload.py", line 237, in main
    replay = json.loads(infile.read())
  File "/home/adam/miniconda3/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 11: invalid start byte
```

**Comment by rooklift** [comment]
Sorry, I meant *after unzipping* the zip file, you can rename it to `replay.json` (or `anything.json`).

**Comment by AdamStelmaszczyk** [comment]
Thanks, it works :)

**Comment by rooklift** [comment]
By the way, the script now handles this in a better way, and should autodetect the format regardless of file extension (though still not handling zip files).
